defmodule CustomizeAshAuthentication.Repo.Migrations.AddProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :first_name, :text
      add :last_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "profiles_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:profiles, [:user_id])

    create unique_index(:profiles, [:user_id], name: "profiles_unique_user_index")
  end

  def down do
    drop_if_exists unique_index(:profiles, [:user_id], name: "profiles_unique_user_index")

    drop_if_exists index(:profiles, [:user_id])

    drop constraint(:profiles, "profiles_user_id_fkey")

    drop table(:profiles)
  end
end
