defmodule CustomizeAshAuthentication.Repo.Migrations.AddUserAcknowledgement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_acknowledgements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ip, :text, null: false
      add :user_agent, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_acknowledgements_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :document_version_id,
          references(:document_versions,
            column: :id,
            name: "user_acknowledgements_document_version_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:user_acknowledgements, [:user_id])

    create index(:user_acknowledgements, [:document_version_id])

    create unique_index(:user_acknowledgements, [:user_id, :document_version_id],
             name: "user_acknowledgements_unique_user_document_version_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_acknowledgements, [:user_id, :document_version_id],
                     name: "user_acknowledgements_unique_user_document_version_index"
                   )

    drop_if_exists index(:user_acknowledgements, [:document_version_id])

    drop_if_exists index(:user_acknowledgements, [:user_id])

    drop constraint(:user_acknowledgements, "user_acknowledgements_user_id_fkey")

    drop constraint(:user_acknowledgements, "user_acknowledgements_document_version_id_fkey")

    drop table(:user_acknowledgements)
  end
end
